name: lights
version: "0.1"
summary: This is a Philips hue light control snap app 
description: 
  This app shows how to control the philips hue bulbs
confinement: strict
grade: stable

apps:
  lights:
    command: lights
    # daemon: simple
    plugs: [network-bind]

parts:
  node:
    plugin: nodejs
    source: . 
